# Generated by Django 5.1.2 on 2024-10-25 08:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShortedUrl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_url', models.URLField(verbose_name='Оригинальная ссылка')),
                ('short_url', models.CharField(max_length=15, unique=True, verbose_name='Сокращенная ссылка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('is_favorite', models.BooleanField(default=False, verbose_name='Является избранной ссылкой')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Автор ссылки')),
            ],
            options={
                'verbose_name': 'Сокращенная ссылка',
                'verbose_name_plural': 'Сокращенные ссылки',
            },
        ),
    ]
