# Generated by Django 5.1.2 on 2024-10-28 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortedurl',
            name='short_url',
            field=models.CharField(max_length=6, unique=True, verbose_name='Сокращенная ссылка'),
        ),
    ]
