# Generated by Django 5.1.2 on 2024-10-28 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_shortedurl_short_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortedurl',
            name='title',
            field=models.CharField(default='', max_length=50, verbose_name='Название ссылки'),
        ),
    ]
