# Generated by Django 5.1.2 on 2024-10-28 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_qr'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortedurl',
            name='is_only_qr',
            field=models.BooleanField(default=False, verbose_name='Ссылка создавалась исключительно для QR кода'),
        ),
    ]
