# Generated by Django 5.1.2 on 2024-11-03 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_shortedurl_is_only_qr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qr',
            name='title',
            field=models.CharField(default='', max_length=500, verbose_name='Название QR'),
        ),
    ]
