# Generated by Django 5.1.2 on 2024-12-06 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_qr_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qr',
            name='author',
        ),
        migrations.RemoveField(
            model_name='qr',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='qr',
            name='is_favorite',
        ),
        migrations.RemoveField(
            model_name='qr',
            name='original_url',
        ),
        migrations.RemoveField(
            model_name='qr',
            name='qr',
        ),
        migrations.RemoveField(
            model_name='qr',
            name='title',
        ),
        migrations.AddField(
            model_name='qr',
            name='background_color',
            field=models.CharField(default='ffffff', max_length=6, verbose_name='Цвет фона'),
        ),
        migrations.AddField(
            model_name='qr',
            name='is_with_background',
            field=models.BooleanField(default=False, verbose_name='Имеет фон'),
        ),
        migrations.AddField(
            model_name='qr',
            name='logo',
            field=models.FileField(default='logos/operator.png', upload_to='logos', verbose_name='Логотип'),
        ),
        migrations.AddField(
            model_name='qr',
            name='qr_color',
            field=models.CharField(default='101010', max_length=6, verbose_name='Цвет QR кода'),
        ),
        migrations.AddField(
            model_name='qr',
            name='short_url',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.shortedurl', verbose_name='Короткая ссылка, которой соответствует QR'),
            preserve_default=False,
        ),
    ]
